spring:
  application:
    name: apifirst
  datasource:
    driver-class-name: org.h2.Driver
    username: user
    password: pass
    url: "jdbc:h2:mem:prueba_nelson;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
springfox:
  documentation:
    swagger:
      use-model-v3: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
